// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Signage.Infrastructure.Persistence;

#nullable disable

namespace Signage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignageDbContext))]
    [Migration("20261005215817_StaffAccounts")]
    partial class StaffAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Signage.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Signage.Domain.ConversionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AvailableUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresentationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresentationVersionId");

                    b.HasIndex("Status", "AvailableUtc");

                    b.ToTable("ConversionJobs");
                });

            modelBuilder.Entity("Signage.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrowserSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PairedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayingContentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayingPresentationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ScreenGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScreenGroupId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Signage.Domain.PairingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConsumedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedDeviceToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporaryTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedDeviceId");

                    b.HasIndex("CodeHash");

                    b.HasIndex("TemporaryTokenHash")
                        .IsUnique();

                    b.ToTable("PairingSessions");
                });

            modelBuilder.Entity("Signage.Domain.Presentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("Signage.Domain.PresentationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadyUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlideCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PresentationVersions");
                });

            modelBuilder.Entity("Signage.Domain.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndsUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PresentationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublishedBySubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PublishedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScreenGroupId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartsUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresentationVersionId");

                    b.HasIndex("ScreenGroupId", "IsEnabled", "StartsUtc");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Signage.Domain.PublishTarget", b =>
                {
                    b.Property<Guid>("PresentationVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScreenGroupId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndsUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublishWhenReady")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartsUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("PresentationVersionId", "ScreenGroupId");

                    b.HasIndex("ScreenGroupId");

                    b.ToTable("PublishTargets");
                });

            modelBuilder.Entity("Signage.Domain.PublisherAccess", b =>
                {
                    b.Property<string>("IdentitySubject")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScreenGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdentitySubject", "ScreenGroupId");

                    b.HasIndex("ScreenGroupId");

                    b.ToTable("PublisherAccess");
                });

            modelBuilder.Entity("Signage.Domain.ScreenGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScreenGroups");
                });

            modelBuilder.Entity("Signage.Domain.StaffAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSignInUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySubject")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalSubject")
                        .IsUnique();

                    b.HasIndex("Provider", "NormalizedLoginName")
                        .IsUnique();

                    b.ToTable("StaffAccounts");
                });

            modelBuilder.Entity("Signage.Domain.ConversionJob", b =>
                {
                    b.HasOne("Signage.Domain.PresentationVersion", "PresentationVersion")
                        .WithMany("Jobs")
                        .HasForeignKey("PresentationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresentationVersion");
                });

            modelBuilder.Entity("Signage.Domain.Device", b =>
                {
                    b.HasOne("Signage.Domain.ScreenGroup", "ScreenGroup")
                        .WithMany("Devices")
                        .HasForeignKey("ScreenGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ScreenGroup");
                });

            modelBuilder.Entity("Signage.Domain.PairingSession", b =>
                {
                    b.HasOne("Signage.Domain.Device", "ApprovedDevice")
                        .WithMany()
                        .HasForeignKey("ApprovedDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedDevice");
                });

            modelBuilder.Entity("Signage.Domain.PresentationVersion", b =>
                {
                    b.HasOne("Signage.Domain.Presentation", "Presentation")
                        .WithMany("Versions")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Signage.Domain.Publication", b =>
                {
                    b.HasOne("Signage.Domain.PresentationVersion", "PresentationVersion")
                        .WithMany()
                        .HasForeignKey("PresentationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Signage.Domain.ScreenGroup", "ScreenGroup")
                        .WithMany("Publications")
                        .HasForeignKey("ScreenGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PresentationVersion");

                    b.Navigation("ScreenGroup");
                });

            modelBuilder.Entity("Signage.Domain.PublishTarget", b =>
                {
                    b.HasOne("Signage.Domain.PresentationVersion", "PresentationVersion")
                        .WithMany("PublishTargets")
                        .HasForeignKey("PresentationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Signage.Domain.ScreenGroup", "ScreenGroup")
                        .WithMany()
                        .HasForeignKey("ScreenGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PresentationVersion");

                    b.Navigation("ScreenGroup");
                });

            modelBuilder.Entity("Signage.Domain.PublisherAccess", b =>
                {
                    b.HasOne("Signage.Domain.ScreenGroup", "ScreenGroup")
                        .WithMany()
                        .HasForeignKey("ScreenGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScreenGroup");
                });

            modelBuilder.Entity("Signage.Domain.Presentation", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Signage.Domain.PresentationVersion", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("PublishTargets");
                });

            modelBuilder.Entity("Signage.Domain.ScreenGroup", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
