import { expect, test, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';

async function screenshot(page: Page, name: string) {
  if (!process.env.SIGNAGE_QA_DIR) return;
  await mkdir(process.env.SIGNAGE_QA_DIR, { recursive: true });
  await page.screenshot({ path: join(process.env.SIGNAGE_QA_DIR, name + '.png'), fullPage: true });
}

test('presentation folders, archive, restore and confirmed deletion work on desktop and mobile', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/dev-login?asRole=admin');
  await page.goto('/Publish');
  await page.locator('input[type=file]').setInputFiles(resolve(import.meta.dirname, '../../../output/playwright/fixtures/playwright-welcome.pptx'));
  await page.getByLabel('Presentation name').fill('Library lifecycle test');
  await page.getByLabel('Publish when ready', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Prepared for preview' })).toBeVisible({ timeout: 60_000 });
  await page.goto('/Admin/Presentations');
  await expect(page).toHaveTitle('Presentations · School Signage');
  await expect(page.getByRole('heading', { name: 'Presentations', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New folder', exact: true }).click();
  await page.getByLabel('New folder', { exact: true }).fill('School events');
  await page.getByRole('button', { name: 'Create folder' }).click();
  await expect(page.getByRole('status')).toContainText('Folder created.');
  await expect(page.getByRole('button', { name: 'Rename', exact: true })).toBeVisible();
  await expect(page.locator('[data-presentation-id]')).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Folders', exact: true }).getByRole('link', { name: 'All presentations' }).click();

  const card = page.locator('[data-presentation-id]').filter({ has: page.getByRole('heading', { name: 'Library lifecycle test', exact: true }) });
  await card.getByRole('button', { name: 'More actions for Library lifecycle test' }).click();
  await card.getByRole('button', { name: 'School events', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Presentation moved.');
  await page.getByRole('navigation', { name: 'Folders', exact: true }).getByRole('link', { name: /School events/ }).click();
  await expect(card).toBeVisible();
  await page.getByRole('button', { name: 'Rename', exact: true }).click();
  await page.getByLabel('Folder name', { exact: true }).fill('Assemblies');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Folder renamed.');
  await expect(page.getByRole('navigation', { name: 'Folders', exact: true }).getByRole('link', { name: /Assemblies/ })).toBeVisible();
  await screenshot(page, 'library-desktop');

  await card.getByRole('button', { name: 'More actions for Library lifecycle test' }).click();
  await card.getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(card).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Presentation library' }).getByRole('link', { name: /Archived/ }).click();
  await expect(card).toBeVisible();
  await expect(card.getByRole('button', { name: 'Publish', exact: true })).toHaveCount(0);
  await expect(card.getByRole('link', { name: 'Preview', exact: true })).toBeVisible();
  await card.getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(card).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Presentation library' }).getByRole('link', { name: /Active/ }).click();
  await expect(card).toBeVisible();

  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Remove folder' }).click();
  await expect(page.getByRole('button', { name: 'Rename', exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Remove folder' }).click();
  await expect(page.getByRole('status')).toContainText('Folder removed.');
  await page.getByRole('navigation', { name: 'Folders', exact: true }).getByRole('link', { name: /Unfiled/ }).click();
  await expect(card).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Unfiled', exact: true })).toBeVisible();

  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'New folder', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await screenshot(page, 'library-mobile');
  await card.getByRole('button', { name: 'More actions for Library lifecycle test' }).click();
  page.once('dialog', dialog => dialog.dismiss());
  await card.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(card).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await card.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(card).toHaveCount(0);
  await expect(page.getByRole('status')).toContainText('Presentation and its versions deleted.');
  expect(errors).toEqual([]);
});

test('a player retains its pairing through device archive and restore, then deletion requires re-pairing', async ({ context }) => {
  const admin = await context.newPage();
  const errors: string[] = [];
  admin.on('pageerror', error => errors.push(error.message));
  admin.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const player = await context.newPage();
  await player.goto('/player/');
  await expect(player.locator('#pairing-code')).toBeVisible();
  const code = (await player.locator('#pairing-code').textContent())!.trim();
  await admin.goto('/dev-login?asRole=admin');
  await admin.goto('/Admin/Pairing');
  await admin.getByLabel('Pairing code').fill(code);
  await admin.getByLabel('Device name').fill('Retired library display');
  await admin.getByLabel('Screen group').selectOption({ label: 'Reception' });
  const assignment = player.waitForResponse(response => response.url().endsWith('/api/player/assignment') && response.status() === 200);
  await admin.getByRole('button', { name: 'Approve device' }).click();
  await assignment;
  await admin.goto('/Admin/Devices');
  await expect(admin).toHaveTitle('Devices · School Signage');
  const row = admin.getByRole('row').filter({ hasText: 'Retired library display' });
  await row.getByRole('button', { name: 'More actions for Retired library display' }).click();
  await row.getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(row).toHaveCount(0);
  const denied = player.waitForResponse(response => response.url().endsWith('/api/player/assignment') && response.status() === 403);
  await player.reload();
  await denied;
  await expect(player.locator('#pairing-code')).toBeHidden();
  await admin.getByRole('navigation', { name: 'Device library' }).getByRole('link', { name: /Archived/ }).click();
  await expect(row.getByText('Archived', { exact: true })).toBeVisible();
  await screenshot(admin, 'devices-archived');
  await row.getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(row).toHaveCount(0);
  const allowed = player.waitForResponse(response => response.url().endsWith('/api/player/assignment') && response.status() === 200);
  await player.reload();
  await allowed;
  await expect(player.locator('#pairing-code')).toBeHidden();
  await admin.getByRole('navigation', { name: 'Device library' }).getByRole('link', { name: /Active/ }).click();
  await expect(row).toBeVisible();
  await row.getByRole('button', { name: 'More actions for Retired library display' }).click();
  admin.once('dialog', dialog => dialog.dismiss());
  await row.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(row).toBeVisible();
  admin.once('dialog', dialog => dialog.accept());
  await row.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(row).toHaveCount(0);
  await expect(admin.getByRole('status')).toContainText('Device deleted.');
  await player.reload();
  await expect(player.locator('#pairing-code')).toBeVisible();
  expect(errors).toEqual([]);
});
